### ISSUE TITLE
Build is failing on arch linux

### ISSUE THREAD

**Issue by SolarAquarion** [stonewell/wxglterm#3]
/tmp/ccbeGNMM.ltrans8.ltrans.o: In function `os_openpty_impl.isra.90':
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/build/src/app/./Modules/posixmodule.c:5811: undefined reference to `openpty'
/tmp/ccbeGNMM.ltrans8.ltrans.o: In function `os_forkpty_impl.isra.89':
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/build/src/app/./Modules/posixmodule.c:5905: undefined reference to `forkpty'
collect2: error: ld returned 1 exit status
make[2]: *** [src/app/CMakeFiles/wxglterm.dir/build.make:105: src/app/wxglterm] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: src/app/CMakeFiles/wxglterm.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by stonewell** [comment]
add util lib to the link options. please test the latest version

**Comment by SolarAquarion** [comment]
I did add -lutil

**Comment by SolarAquarion** [comment]
/tmp/ccv2s7SA.ltrans8.ltrans.o: In function `os_openpty_impl.isra.90':
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/build/src/app/./Modules/posixmodule.c:5811: undefined reference to `openpty'
/tmp/ccv2s7SA.ltrans8.ltrans.o: In function `os_forkpty_impl.isra.89':
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/build/src/app/./Modules/posixmodule.c:5905: undefined reference to `forkpty'
collect2: error: ld returned 1 exit status

i'm still getting this

**Comment by SolarAquarion** [comment]
@stonewell why is wxglterm summoning "python" c libraries

**Comment by SolarAquarion** [comment]
i figured out what the issue was lol
