### ISSUE TITLE
pybind11 wrong install dirs

### ISSUE THREAD

**Issue by SolarAquarion** [stonewell/wxglterm#5]
wxglterm-git /home/
wxglterm-git /home/solaraquarion/
wxglterm-git /home/solaraquarion/pkgbuild/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/attr.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/buffer_info.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/cast.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/chrono.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/common.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/complex.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/class.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/common.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/descr.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/init.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/internals.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/detail/typeid.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/eigen.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/embed.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/eval.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/functional.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/iostream.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/numpy.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/operators.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/options.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/pybind11.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/pytypes.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/stl.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/include/pybind11/stl_bind.h
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/FindPythonLibsNew.cmake
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/pybind11Config.cmake
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/pybind11ConfigVersion.cmake
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/pybind11Targets.cmake
wxglterm-git /home/solaraquarion/pkgbuild/wxglterm-git/src/build/pybind11_install/share/cmake/pybind11/pybind11Tools.cmake

**Comment by stonewell** [comment]
pybind11 is a c++ template library which means only header needed. wxglterm will not install it to systen folder

**Comment by SolarAquarion** [comment]
shouldn't the install thing remove the packages in the home after installing the directories?

**Comment by SolarAquarion** [comment]
"make install all" remove the pybind directories that were built

**Comment by SolarAquarion** [comment]
[PKGBUILD.txt](https://github.com/stonewell/wxglterm/files/1778537/PKGBUILD.txt)

see my PKGBUILD i suppose
