### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [stonewell/wxglterm#7]
```
-- Build files have been written to: /home/solaraquarion/build/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite-build
[ 76%] Performing build step for 'scite'
Scanning dependencies of target scite_cross_platform
[  4%] Building CXX object CMakeFiles/scite_cross_platform.dir/src/Cookie.cxx.o
/home/solaraquarion/build/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/Cookie.cxx:14:10: fatal error: Scintilla.h: No such file or directory
 #include "Scintilla.h"
          ^~~~~~~~~~~~~
compilation terminated.
make[5]: *** [CMakeFiles/scite_cross_platform.dir/build.make:63: CMakeFiles/scite_cross_platform.dir/src/Cookie.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:68: CMakeFiles/scite_cross_platform.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [src/external_plugins/scintilla_editor/CMakeFiles/scite.dir/build.make:110: src/external_plugins/scintilla_editor/scite-prefix/src/scite-stamp/scite-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1218: src/external_plugins/scintilla_editor/CMakeFiles/scite.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by SolarAquarion** [comment]
shouldn't you be adding this to that folder? http://www.cs.cmu.edu/~djseo/scintilla/include/Scintilla.h

**Comment by stonewell** [comment]
you should build scite plugin, it disabled by default and for test purpose. do you and -DBUILD_SCINTILLA_EDITOR=ON to cmake command?
please disable by -DBUILD_SCINTILLA_EDITOR=OFF

**Comment by SolarAquarion** [comment]
I'm going to be packaging Scintella headers

**Comment by stonewell** [comment]
scintilla plugin is not working, package it has no value

**Comment by SolarAquarion** [comment]
Having it at least compile is a plus at least, no?

**Comment by SolarAquarion** [comment]
I should disable it

**Comment by SolarAquarion** [comment]
canning dependencies of target scintilla_editor
[ 85%] Building CXX object
src/external_plugins/scintilla_editor/CMakeFiles/scintilla_editor.dir/platform.cxx.o
[ 85%] Building CXX object
src/external_plugins/scintilla_editor/CMakeFiles/scintilla_editor.dir/window.cxx.o
[ 86%] Building CXX object
src/external_plugins/scintilla_editor/CMakeFiles/scintilla_editor.dir/surface.cxx.o
[ 88%] Building CXX object
src/external_plugins/scintilla_editor/CMakeFiles/scintilla_editor.dir/scintilla_editor_plugin.cxx.o
[ 88%] Building CXX object
src/external_plugins/scintilla_editor/CMakeFiles/scintilla_editor.dir/scintilla_editor_buffer.cxx.o
In file included from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scite_impl.h:31:0,
                 from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scintilla_editor_buffer.cxx:62:
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/StyleWriter.h:25:7:
error: ‘ScintillaWindow’ in namespace ‘GUI’ does not name a type
  GUI::ScintillaWindow &sw;
       ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/StyleWriter.h:31:43:
error: expected ‘)’ before ‘&’ token
  explicit TextReader(GUI::ScintillaWindow &sw_);
                                           ^
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/StyleWriter.h:74:44:
error: expected ‘)’ before ‘&’ token
  explicit StyleWriter(GUI::ScintillaWindow &sw_);
                                            ^
In file included from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scite_impl.h:39:0,
                 from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scintilla_editor_buffer.cxx:62:
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/MatchMarker.h:14:40:
error: ‘ScintillaWindow’ is not a member of ‘GUI’
 std::vector<LineRange> LinesBreak(GUI::ScintillaWindow *pSci);
                                        ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/MatchMarker.h:14:40:
note: suggested alternative: ‘ScintillaPrimitive’
 std::vector<LineRange> LinesBreak(GUI::ScintillaWindow *pSci);
                                        ^~~~~~~~~~~~~~~
                                        ScintillaPrimitive
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/MatchMarker.h:14:57:
error: ‘pSci’ was not declared in this scope
 std::vector<LineRange> LinesBreak(GUI::ScintillaWindow *pSci);
                                                         ^~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/MatchMarker.h:17:7:
error: ‘ScintillaWindow’ in namespace ‘GUI’ does not name a type
  GUI::ScintillaWindow *pSci;
       ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/MatchMarker.h:27:18:
error: ‘GUI::ScintillaWindow’ has not been declared
  void StartMatch(GUI::ScintillaWindow *pSci_,
                  ^~~
In file included from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scite_impl.h:40:0,
                 from
/home/solaraquarion/pkgbuild/wxglterm-git/src/wxglterm/src/external_plugins/scintilla_editor/scintilla_editor_buffer.cxx:62:
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:422:7:
error: ‘ScintillaWindow’ in namespace ‘GUI’ does not name a type
  GUI::ScintillaWindow wEditor;
       ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:423:7:
error: ‘ScintillaWindow’ in namespace ‘GUI’ does not name a type
  GUI::ScintillaWindow wOutput;
       ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:424:7:
error: ‘ScintillaWindow’ in namespace ‘GUI’ does not name a type
  GUI::ScintillaWindow *pwFocussed;
       ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:589:23:
error: ‘GUI::ScintillaWindow’ has not been declared
  static void GetRange(GUI::ScintillaWindow &win, int start, int end, char
*text);
                       ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:700:36:
error: ‘GUI::ScintillaWindow’ has not been declared
  static std::string GetRangeString(GUI::ScintillaWindow &win, int
selStart, int selEnd);
                                    ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:701:43:
error: ‘GUI::ScintillaWindow’ has not been declared
  virtual std::string GetRangeInUIEncoding(GUI::ScintillaWindow &win, int
selStart, int selEnd);
                                           ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:702:29:
error: ‘GUI::ScintillaWindow’ has not been declared
  static std::string GetLine(GUI::ScintillaWindow &win, int line);
                             ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:703:19:
error: ‘GUI::ScintillaWindow’ has not been declared
  void RangeExtend(GUI::ScintillaWindow &wCurrent, int &selStart, int
&selEnd,
                   ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:705:33:
error: ‘GUI::ScintillaWindow’ has not been declared
  std::string RangeExtendAndGrab(GUI::ScintillaWindow &wCurrent, int
&selStart, int &selEnd,
                                 ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:825:33:
error: ‘GUI::ScintillaWindow’ has not been declared
  static void EnsureRangeVisible(GUI::ScintillaWindow &win, int posStart,
int posEnd, bool enforcePolicy = true);
                                 ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:860:19:
error: ‘GUI::ScintillaWindow’ has not been declared
  void ContextMenu(GUI::ScintillaWindow &wSource, GUI::Point pt,
GUI::Window wCmd);
                   ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:883:23:
error: ‘GUI::ScintillaWindow’ has not been declared
  void SetAboutMessage(GUI::ScintillaWindow &wsci, const char *appTitle);
                       ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:905:19:
error: ‘GUI::ScintillaWindow’ has not been declared
  void SetOneStyle(GUI::ScintillaWindow &win, int style, const
StyleDefinition &sd);
                   ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:906:21:
error: ‘GUI::ScintillaWindow’ has not been declared
  void SetStyleBlock(GUI::ScintillaWindow &win, const char *lang, int
start, int last);
                     ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:907:19:
error: ‘GUI::ScintillaWindow’ has not been declared
  void SetStyleFor(GUI::ScintillaWindow &win, const char *lang);
                   ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:908:30:
error: ‘GUI::ScintillaWindow’ has not been declared
  static void SetOneIndicator(GUI::ScintillaWindow &win, int indicator,
const IndicatorDefinition &ind);
                              ^~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:997:26:
error: variable or field ‘WindowSetFocus’ declared void
 void WindowSetFocus(GUI::ScintillaWindow &w);
                          ^~~~~~~~~~~~~~~
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:997:26:
error: ‘ScintillaWindow’ is not a member of ‘GUI’
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:997:26:
note: suggested alternative: ‘ScintillaPrimitive’
 void WindowSetFocus(GUI::ScintillaWindow &w);
                          ^~~~~~~~~~~~~~~
                          ScintillaPrimitive
/home/solaraquarion/pkgbuild/wxglterm-git/src/build/src/external_plugins/scintilla_editor/scite-prefix/src/scite/src/SciTEBase.h:997:43:
error: ‘w’ was not declared in this scope
 void WindowSetFocus(GUI::ScintillaWindow &w);

**Comment by stonewell** [comment]
if you really want to do it, then since the cmake project will download scintilla project from github, which contains the header, so I guess it caused by a download fail, could you run make update_external instead to make sure everything is downloads.
but I don't think it is any value to compile a test plugin, I should remove them from current project and create a new project for testing
